// src/constants/mockData.ts
import type { Entry } from '@/types'

export const MOCK_ENTRIES: Entry[] = [
  {
    id: '1', concept: 'to love', category: 'verb',
    tags: ['duygu', 'temel'], cognateGroup: 'amor-group',
    translations: {
      it:  { value: 'amare',       romanization: '',                notes: '< Lat. amare'   },
      es:  { value: 'amar',        romanization: '',                notes: '< Lat. amare'   },
      fr:  { value: 'aimer',       romanization: '',                notes: '< Lat. amare'   },
      la:  { value: 'amare',       romanization: '',                notes: 'kök'             },
      de:  { value: 'lieben',      romanization: '',                notes: ''               },
      en:  { value: 'to love',     romanization: '',                notes: ''               },
      ru:  { value: 'любить',      romanization: "lyubit'",         notes: ''               },
      ja:  { value: '愛する',       romanization: 'ai suru',         notes: ''               },
      ko:  { value: '사랑하다',     romanization: 'saranghada',      notes: ''               },
      zh:  { value: '爱',           romanization: 'ài',             notes: ''               },
      el:  { value: 'αγαπώ',       romanization: 'agapó',           notes: ''               },
      hy:  { value: 'սիրել',       romanization: 'sirel',           notes: ''               },
      kbd: { value: 'фIэлIыкIын',  romanization: "f'aliqin",        notes: ''               },
    },
  },
  {
    id: '2', concept: 'water', category: 'noun',
    tags: ['doğa', 'temel'], cognateGroup: 'aqua-group',
    translations: {
      it:  { value: 'acqua',  romanization: '',       notes: '< Lat. aqua' },
      es:  { value: 'agua',   romanization: '',       notes: '< Lat. aqua' },
      fr:  { value: 'eau',    romanization: '',       notes: '< Lat. aqua' },
      la:  { value: 'aqua',   romanization: '',       notes: 'kök'         },
      de:  { value: 'Wasser', romanization: '',       notes: ''           },
      en:  { value: 'water',  romanization: '',       notes: ''           },
      ru:  { value: 'вода',   romanization: 'voda',  notes: ''           },
      ja:  { value: '水',      romanization: 'mizu',  notes: ''           },
      ko:  { value: '물',      romanization: 'mul',   notes: ''           },
      zh:  { value: '水',      romanization: 'shuǐ', notes: ''           },
      el:  { value: 'νερό',   romanization: 'neró',  notes: ''           },
      hy:  { value: 'ջուր',   romanization: 'jur',   notes: ''           },
      kbd: { value: 'псы',    romanization: 'psy',   notes: ''           },
    },
  },
  {
    id: '3', concept: 'beautiful', category: 'adj',
    tags: ['tanımlama'], cognateGroup: 'beau-group',
    translations: {
      it:  { value: 'bello',     romanization: '',           notes: '< Lat. bellus' },
      es:  { value: 'bello',     romanization: '',           notes: '< Lat. bellus' },
      fr:  { value: 'beau',      romanization: '',           notes: '< Lat. bellus' },
      la:  { value: 'bellus',    romanization: '',           notes: 'kök'           },
      de:  { value: 'schön',     romanization: '',           notes: ''             },
      en:  { value: 'beautiful', romanization: '',           notes: ''             },
      ru:  { value: 'красивый',  romanization: 'krasiviy',  notes: ''             },
      ja:  { value: '美しい',     romanization: 'utsukushii',notes: ''             },
      ko:  { value: '아름다운',   romanization: 'areumdaun', notes: ''             },
      zh:  { value: '美丽',       romanization: 'měilì',     notes: ''             },
      el:  { value: 'όμορφος',   romanization: 'ómorfos',   notes: ''             },
      hy:  { value: 'գեղեցիկ',  romanization: 'gegetsik',  notes: ''             },
      kbd: { value: 'дахэ',      romanization: 'dahe',      notes: ''             },
    },
  },
  {
    id: '4', concept: 'I speak', category: 'phrase',
    tags: ['dil', 'iletişim'], cognateGroup: '',
    translations: {
      it:  { value: 'io parlo',        romanization: '',                     notes: '' },
      es:  { value: 'yo hablo',        romanization: '',                     notes: '' },
      fr:  { value: 'je parle',        romanization: '',                     notes: '' },
      la:  { value: 'loquor',          romanization: '',                     notes: '' },
      de:  { value: 'ich spreche',     romanization: '',                     notes: '' },
      en:  { value: 'I speak',         romanization: '',                     notes: '' },
      ru:  { value: 'я говорю',        romanization: 'ya govoryu',           notes: '' },
      ja:  { value: '私は話します',      romanization: 'watashi wa hanashimasu', notes: '' },
      ko:  { value: '나는 말합니다',     romanization: 'naneun malhabnida',   notes: '' },
      zh:  { value: '我说话',           romanization: 'wǒ shuōhuà',          notes: '' },
      el:  { value: 'μιλάω',           romanization: 'miláo',               notes: '' },
      hy:  { value: 'ես խոսում եմ',    romanization: 'yes khoshum yem',     notes: '' },
      kbd: { value: 'сэгущIэ',         romanization: "sag'usch'e",           notes: '' },
    },
  },
]
